### ISSUE TITLE
收藏的按时间排序

### ISSUE THREAD

**Issue by BinotaLiu** [bangumi/issues#15]
Source: https://bgm.tv/group/topic/312521
收藏的「按时间排序」是按照加入收藏时间排的，希望能选择是按什么时间排序的，添加按作品发布时间排序方式

**Comment by wattlebird** [comment]
Currently, not all subjects have their outcoming date. The outcoming date is maintained by Bangumi Wiki editors, and the outcoming date cannot be unified according to a specific standard. Besides for some subjects, there are no outcoming date at all. The only thing we can ensure that when one user execute an action on a subject, that action issues a time, and we can sort by that time.

For me, I think it is more reasonable to sort subjects by user favorite time. That reflects a user's sequence of subject selection, and that contains rich information of user's behavior.

**Comment by fireattack** [comment]
Having two ways won't hurt anyone.

**Comment by wattlebird** [comment]
It is not an issue or another possibility for another way of sorting: technically, sorting by outcoming date is intractable because there are no unified term indicating the outcoming date.

For example, the outcoming date of http://chii.in/subject/265 is 1995/10/04, which is indicated by label "放送开始". But not all subjects have the label "放送开始", such as this: http://chii.in/subject/3302, which outcoming date is indicated by "上映年度". And some subjects have incomplete outcoming date such as http://chii.in/subject/158035, and http://chii.in/subject/116247, the latter of which does not even have an outcoming date.

Technically, we should unify the format of date in wiki system first. That includes unifying the representation of datetime. Handling multiple outcoming date such as http://chii.in/subject/142596 should also be considered. And the term of outcoming date should also be unified or, at least, have a priority.

The most difficult thing is not the system, but the people who creates each subject because wiki editors with different preferences would insist their own style when giving the date of each subject.

**Comment by fireattack** [comment]
It doesn't matter if it's 放送开始 or 上映年度... Bangumi is able to recognize them all. Hell, we can already browse animes by date: http://chii.in/anime/browser/airtime/2013-6 there is literally no technical barrier to implement sort-by-date function.

And about the ones don't have date.. yeah sure it happens, just put them on the end of the list until their dates are added. Why it's a big deal? Every single big database in the world is not complete to an extent and will never be. Just like how Bangumi sorts your anime when some of them are not ranked by you. We should add this feature first (I mean, in case we *decided* this feature is useful) then people can start fix the date format, not the other way around. 

I mean, this topic should be focus on **why we need it** NOT **how we implement it**.

**Comment by wattlebird** [comment]
@Sai , would you please reveal the accuracy, precision, recall and F1 score of the date recognition function that @fireattack mentioned in the first paragraph?

**Comment by Sai** [comment]
Deployed. Enjoy!
